# Generated by Django 3.0.3 on 2020-02-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycustomuser',
            name='favorite_color',
        ),
    ]
