# Generated by Django 3.0.3 on 2020-02-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_remove_mycustomuser_favorite_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='favorite_color',
            field=models.CharField(default='Red', max_length=20),
        ),
    ]
