# Generated by Django 3.0.3 on 2020-02-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_mycustomuser_favorite_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mycustomuser',
            name='favorite_color',
            field=models.CharField(max_length=20),
        ),
    ]
